---
# playbook used to provision apps common to all my environments

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - check-requirements
    - update-packages
    - env-setup
    - docker
    - tmux
    - webcam
    - java
    - nodejs
    - aws-greengrass-iot
...
