---
# tasks file for docker

- name: Install docker package
  apt:
    state: latest
    name: ['docker-compose', 'docker.io']

- name: Add user pi to group docker
  user:
    name: pi
    groups: docker
    append: yes

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
    state: started
...